# Generated by Django 2.1.8 on 2019-10-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=32)),
                ('class_name', models.CharField(max_length=32)),
                ('rx_time', models.DateField()),
                ('yx', models.CharField(max_length=32)),
            ],
        ),
    ]
